### ISSUE TITLE
Example page throws a 404 Error

### ISSUE THREAD

**Issue by kjprice** [rubynor/table-fixed-header#22]
I just clicked on the [link to see an example](http://rubynor.com/table-fixed-header/example.html) and am seeing a 404 error.

![image](https://cloud.githubusercontent.com/assets/2319673/15436072/a435ddc6-1e85-11e6-897f-bfbd6f4c438b.png)

Is there another example we could use? Maybe a jsfiddle?

**Comment by hildevestol** [comment]
Thank for your message! We forgot this example when we created a new webpage 😄 
The example is back up on the page, and the link is working again 😄

**Comment by kjprice** [comment]
Yay! Sounds like an easy fix. Thanks!
